// Kur'an-ı Kerim Verileri
// NOT: Bu dosyada tüm 114 surenin yapısı var ama ayetler placeholder olarak
// Gerçek metin için tam Kur'an JSON'ını eklemeniz gerekiyor

// Her sure için placeholder ayet oluştur
function createPlaceholderAyahs(suraNumber, count) {
    const ayahs = [];
    for (let i = 1; i <= count; i++) {
        ayahs.push({
            number: i,
            text: `Bu ${suraNumber}. surenin ${i}. ayetidir. Lütfen gerçek Kur'an verilerini ekleyin.`
        });
    }
    return ayahs;
}

const QURAN_DATA = {
    surahs: [
        {
            number: 1,
            name: "Fâtiha",
            numberOfAyahs: 7,
            ayahs: [
                { number: 1, text: "Rahmân ve Rahîm olan Allah'ın adıyla." },
                { number: 2, text: "Hamd, âlemlerin Rabbi Allah'a mahsustur." },
                { number: 3, text: "O, Rahmân'dır, Rahîm'dir." },
                { number: 4, text: "O, din gününün (hesap ve ceza gününün) mâlikidir." },
                { number: 5, text: "Yalnız sana ibadet eder ve yalnız senden yardım dileriz." },
                { number: 6, text: "Bizi dosdoğru yola ilet." },
                { number: 7, text: "Kendilerine nimet verdiklerinin yoluna; gazaba uğramışların ve sapmışların yoluna değil." }
            ]
        },
        { number: 2, name: "Bakara", numberOfAyahs: 286, ayahs: createPlaceholderAyahs(2, 286) },
        { number: 3, name: "Âl-i İmrân", numberOfAyahs: 200, ayahs: createPlaceholderAyahs(3, 200) },
        { number: 4, name: "Nisâ", numberOfAyahs: 176, ayahs: createPlaceholderAyahs(4, 176) },
        { number: 5, name: "Mâide", numberOfAyahs: 120, ayahs: createPlaceholderAyahs(5, 120) },
        { number: 6, name: "En'âm", numberOfAyahs: 165, ayahs: createPlaceholderAyahs(6, 165) },
        { number: 7, name: "A'râf", numberOfAyahs: 206, ayahs: createPlaceholderAyahs(7, 206) },
        { number: 8, name: "Enfâl", numberOfAyahs: 75, ayahs: createPlaceholderAyahs(8, 75) },
        { number: 9, name: "Tevbe", numberOfAyahs: 129, ayahs: createPlaceholderAyahs(9, 129) },
        { number: 10, name: "Yûnus", numberOfAyahs: 109, ayahs: createPlaceholderAyahs(10, 109) },
        { number: 11, name: "Hûd", numberOfAyahs: 123, ayahs: createPlaceholderAyahs(11, 123) },
        { number: 12, name: "Yûsuf", numberOfAyahs: 111, ayahs: createPlaceholderAyahs(12, 111) },
        { number: 13, name: "Ra'd", numberOfAyahs: 43, ayahs: createPlaceholderAyahs(13, 43) },
        { number: 14, name: "İbrâhîm", numberOfAyahs: 52, ayahs: createPlaceholderAyahs(14, 52) },
        { number: 15, name: "Hicr", numberOfAyahs: 99, ayahs: createPlaceholderAyahs(15, 99) },
        { number: 16, name: "Nahl", numberOfAyahs: 128, ayahs: createPlaceholderAyahs(16, 128) },
        { number: 17, name: "İsrâ", numberOfAyahs: 111, ayahs: createPlaceholderAyahs(17, 111) },
        { number: 18, name: "Kehf", numberOfAyahs: 110, ayahs: createPlaceholderAyahs(18, 110) },
        { number: 19, name: "Meryem", numberOfAyahs: 98, ayahs: createPlaceholderAyahs(19, 98) },
        { number: 20, name: "Tâhâ", numberOfAyahs: 135, ayahs: createPlaceholderAyahs(20, 135) },
        { number: 21, name: "Enbiyâ", numberOfAyahs: 112, ayahs: createPlaceholderAyahs(21, 112) },
        { number: 22, name: "Hacc", numberOfAyahs: 78, ayahs: createPlaceholderAyahs(22, 78) },
        { number: 23, name: "Mü'minûn", numberOfAyahs: 118, ayahs: createPlaceholderAyahs(23, 118) },
        { number: 24, name: "Nûr", numberOfAyahs: 64, ayahs: createPlaceholderAyahs(24, 64) },
        { number: 25, name: "Furkān", numberOfAyahs: 77, ayahs: createPlaceholderAyahs(25, 77) },
        { number: 26, name: "Şuarâ", numberOfAyahs: 227, ayahs: createPlaceholderAyahs(26, 227) },
        { number: 27, name: "Neml", numberOfAyahs: 93, ayahs: createPlaceholderAyahs(27, 93) },
        { number: 28, name: "Kasas", numberOfAyahs: 88, ayahs: createPlaceholderAyahs(28, 88) },
        { number: 29, name: "Ankebût", numberOfAyahs: 69, ayahs: createPlaceholderAyahs(29, 69) },
        { number: 30, name: "Rûm", numberOfAyahs: 60, ayahs: createPlaceholderAyahs(30, 60) },
        { number: 31, name: "Lokmân", numberOfAyahs: 34, ayahs: createPlaceholderAyahs(31, 34) },
        { number: 32, name: "Secde", numberOfAyahs: 30, ayahs: createPlaceholderAyahs(32, 30) },
        { number: 33, name: "Ahzâb", numberOfAyahs: 73, ayahs: createPlaceholderAyahs(33, 73) },
        { number: 34, name: "Sebe'", numberOfAyahs: 54, ayahs: createPlaceholderAyahs(34, 54) },
        { number: 35, name: "Fâtır", numberOfAyahs: 45, ayahs: createPlaceholderAyahs(35, 45) },
        { number: 36, name: "Yâsîn", numberOfAyahs: 83, ayahs: createPlaceholderAyahs(36, 83) },
        { number: 37, name: "Sâffât", numberOfAyahs: 182, ayahs: createPlaceholderAyahs(37, 182) },
        { number: 38, name: "Sâd", numberOfAyahs: 88, ayahs: createPlaceholderAyahs(38, 88) },
        { number: 39, name: "Zümer", numberOfAyahs: 75, ayahs: createPlaceholderAyahs(39, 75) },
        { number: 40, name: "Mü'min", numberOfAyahs: 85, ayahs: createPlaceholderAyahs(40, 85) },
        { number: 41, name: "Fussilet", numberOfAyahs: 54, ayahs: createPlaceholderAyahs(41, 54) },
        { number: 42, name: "Şûrâ", numberOfAyahs: 53, ayahs: createPlaceholderAyahs(42, 53) },
        { number: 43, name: "Zuhruf", numberOfAyahs: 89, ayahs: createPlaceholderAyahs(43, 89) },
        { number: 44, name: "Duhân", numberOfAyahs: 59, ayahs: createPlaceholderAyahs(44, 59) },
        { number: 45, name: "Câsiye", numberOfAyahs: 37, ayahs: createPlaceholderAyahs(45, 37) },
        { number: 46, name: "Ahkāf", numberOfAyahs: 35, ayahs: createPlaceholderAyahs(46, 35) },
        { number: 47, name: "Muhammed", numberOfAyahs: 38, ayahs: createPlaceholderAyahs(47, 38) },
        { number: 48, name: "Fetih", numberOfAyahs: 29, ayahs: createPlaceholderAyahs(48, 29) },
        { number: 49, name: "Hucurât", numberOfAyahs: 18, ayahs: createPlaceholderAyahs(49, 18) },
        { number: 50, name: "Kāf", numberOfAyahs: 45, ayahs: createPlaceholderAyahs(50, 45) },
        { number: 51, name: "Zâriyât", numberOfAyahs: 60, ayahs: createPlaceholderAyahs(51, 60) },
        { number: 52, name: "Tûr", numberOfAyahs: 49, ayahs: createPlaceholderAyahs(52, 49) },
        { number: 53, name: "Necm", numberOfAyahs: 62, ayahs: createPlaceholderAyahs(53, 62) },
        { number: 54, name: "Kamer", numberOfAyahs: 55, ayahs: createPlaceholderAyahs(54, 55) },
        { number: 55, name: "Rahmân", numberOfAyahs: 78, ayahs: createPlaceholderAyahs(55, 78) },
        { number: 56, name: "Vâkıa", numberOfAyahs: 96, ayahs: createPlaceholderAyahs(56, 96) },
        { number: 57, name: "Hadîd", numberOfAyahs: 29, ayahs: createPlaceholderAyahs(57, 29) },
        { number: 58, name: "Mücâdele", numberOfAyahs: 22, ayahs: createPlaceholderAyahs(58, 22) },
        { number: 59, name: "Haşr", numberOfAyahs: 24, ayahs: createPlaceholderAyahs(59, 24) },
        { number: 60, name: "Mümtehıne", numberOfAyahs: 13, ayahs: createPlaceholderAyahs(60, 13) },
        { number: 61, name: "Saff", numberOfAyahs: 14, ayahs: createPlaceholderAyahs(61, 14) },
        { number: 62, name: "Cum'a", numberOfAyahs: 11, ayahs: createPlaceholderAyahs(62, 11) },
        { number: 63, name: "Münâfıkūn", numberOfAyahs: 11, ayahs: createPlaceholderAyahs(63, 11) },
        { number: 64, name: "Teğâbün", numberOfAyahs: 18, ayahs: createPlaceholderAyahs(64, 18) },
        { number: 65, name: "Talâk", numberOfAyahs: 12, ayahs: createPlaceholderAyahs(65, 12) },
        { number: 66, name: "Tahrîm", numberOfAyahs: 12, ayahs: createPlaceholderAyahs(66, 12) },
        { number: 67, name: "Mülk", numberOfAyahs: 30, ayahs: createPlaceholderAyahs(67, 30) },
        { number: 68, name: "Kalem", numberOfAyahs: 52, ayahs: createPlaceholderAyahs(68, 52) },
        { number: 69, name: "Hâkka", numberOfAyahs: 52, ayahs: createPlaceholderAyahs(69, 52) },
        { number: 70, name: "Meâric", numberOfAyahs: 44, ayahs: createPlaceholderAyahs(70, 44) },
        { number: 71, name: "Nûh", numberOfAyahs: 28, ayahs: createPlaceholderAyahs(71, 28) },
        { number: 72, name: "Cin", numberOfAyahs: 28, ayahs: createPlaceholderAyahs(72, 28) },
        { number: 73, name: "Müzzemmil", numberOfAyahs: 20, ayahs: createPlaceholderAyahs(73, 20) },
        { number: 74, name: "Müddessir", numberOfAyahs: 56, ayahs: createPlaceholderAyahs(74, 56) },
        { number: 75, name: "Kıyâmet", numberOfAyahs: 40, ayahs: createPlaceholderAyahs(75, 40) },
        { number: 76, name: "İnsan", numberOfAyahs: 31, ayahs: createPlaceholderAyahs(76, 31) },
        { number: 77, name: "Mürselât", numberOfAyahs: 50, ayahs: createPlaceholderAyahs(77, 50) },
        { number: 78, name: "Nebe'", numberOfAyahs: 40, ayahs: createPlaceholderAyahs(78, 40) },
        { number: 79, name: "Nâziât", numberOfAyahs: 46, ayahs: createPlaceholderAyahs(79, 46) },
        { number: 80, name: "Abese", numberOfAyahs: 42, ayahs: createPlaceholderAyahs(80, 42) },
        { number: 81, name: "Tekvîr", numberOfAyahs: 29, ayahs: createPlaceholderAyahs(81, 29) },
        { number: 82, name: "İnfitār", numberOfAyahs: 19, ayahs: createPlaceholderAyahs(82, 19) },
        { number: 83, name: "Mutaffifîn", numberOfAyahs: 36, ayahs: createPlaceholderAyahs(83, 36) },
        { number: 84, name: "İnşikāk", numberOfAyahs: 25, ayahs: createPlaceholderAyahs(84, 25) },
        { number: 85, name: "Burûc", numberOfAyahs: 22, ayahs: createPlaceholderAyahs(85, 22) },
        { number: 86, name: "Târık", numberOfAyahs: 17, ayahs: createPlaceholderAyahs(86, 17) },
        { number: 87, name: "A'lâ", numberOfAyahs: 19, ayahs: createPlaceholderAyahs(87, 19) },
        { number: 88, name: "Ğâşiye", numberOfAyahs: 26, ayahs: createPlaceholderAyahs(88, 26) },
        { number: 89, name: "Fecr", numberOfAyahs: 30, ayahs: createPlaceholderAyahs(89, 30) },
        { number: 90, name: "Beled", numberOfAyahs: 20, ayahs: createPlaceholderAyahs(90, 20) },
        { number: 91, name: "Şems", numberOfAyahs: 15, ayahs: createPlaceholderAyahs(91, 15) },
        { number: 92, name: "Leyl", numberOfAyahs: 21, ayahs: createPlaceholderAyahs(92, 21) },
        { number: 93, name: "Duhâ", numberOfAyahs: 11, ayahs: createPlaceholderAyahs(93, 11) },
        { number: 94, name: "İnşirâh", numberOfAyahs: 8, ayahs: createPlaceholderAyahs(94, 8) },
        { number: 95, name: "Tîn", numberOfAyahs: 8, ayahs: createPlaceholderAyahs(95, 8) },
        { number: 96, name: "Alak", numberOfAyahs: 19, ayahs: createPlaceholderAyahs(96, 19) },
        { number: 97, name: "Kadr", numberOfAyahs: 5, ayahs: createPlaceholderAyahs(97, 5) },
        { number: 98, name: "Beyyine", numberOfAyahs: 8, ayahs: createPlaceholderAyahs(98, 8) },
        { number: 99, name: "Zelzele", numberOfAyahs: 8, ayahs: createPlaceholderAyahs(99, 8) },
        { number: 100, name: "Âdiyât", numberOfAyahs: 11, ayahs: createPlaceholderAyahs(100, 11) },
        { number: 101, name: "Kāria", numberOfAyahs: 11, ayahs: createPlaceholderAyahs(101, 11) },
        { number: 102, name: "Tekâsür", numberOfAyahs: 8, ayahs: createPlaceholderAyahs(102, 8) },
        { number: 103, name: "Asr", numberOfAyahs: 3, ayahs: createPlaceholderAyahs(103, 3) },
        { number: 104, name: "Hümeze", numberOfAyahs: 9, ayahs: createPlaceholderAyahs(104, 9) },
        { number: 105, name: "Fîl", numberOfAyahs: 5, ayahs: createPlaceholderAyahs(105, 5) },
        { number: 106, name: "Kureyş", numberOfAyahs: 4, ayahs: createPlaceholderAyahs(106, 4) },
        { number: 107, name: "Mâûn", numberOfAyahs: 7, ayahs: createPlaceholderAyahs(107, 7) },
        { number: 108, name: "Kevser", numberOfAyahs: 3, ayahs: createPlaceholderAyahs(108, 3) },
        { number: 109, name: "Kâfirûn", numberOfAyahs: 6, ayahs: createPlaceholderAyahs(109, 6) },
        { number: 110, name: "Nasr", numberOfAyahs: 3, ayahs: createPlaceholderAyahs(110, 3) },
        { number: 111, name: "Tebbet", numberOfAyahs: 5, ayahs: createPlaceholderAyahs(111, 5) },
        { number: 112, name: "İhlâs", numberOfAyahs: 4, ayahs: createPlaceholderAyahs(112, 4) },
        { number: 113, name: "Felak", numberOfAyahs: 5, ayahs: createPlaceholderAyahs(113, 5) },
        { number: 114, name: "Nâs", numberOfAyahs: 6, ayahs: createPlaceholderAyahs(114, 6) }
    ]
};

// Konsola bilgi yazdır
console.log('Kur\'an-ı Kerim verileri yüklendi. Toplam:', QURAN_DATA.surahs.length, 'sure');
console.log('NOT: Lütfen gerçek ayet metinlerini eklemek için README.md dosyasındaki talimatları takip edin.');
